name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt || true
      - name: Run linters
        run: |
          black --check . || true
          isort --check-only . || true
          flake8 || true
      - name: Type check
        run: |
          mypy src || true
      - name: Run tests with coverage
        run: |
          pytest --maxfail=1 --disable-warnings -q --cov=src --cov-report=term
